services:
  wordpress:
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ${PWD}:/var/www/html
  mailer:
    image: axllent/mailpit
    ports:
      - "1025"
      - "8025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
  database:
    ports:
      - "3306"
